#!/usr/bin/env node
// Converts the runtime's builtin .js sources into a generated C++ table
// (RuntimeBuiltins.h / RuntimeBuiltins.cpp) compiled into libNativeScript.so.
// Invoked by a custom command in test-app/runtime/CMakeLists.txt.
import { readFileSync, writeFileSync, renameSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { basename, join } from 'node:path';
import { parseArgs } from 'node:util';

const USAGE = `usage: node tools/js2c.mjs --out-dir <dir> [--minify] [--check-dir <dir>] <file.js>...

Generates <dir>/RuntimeBuiltins.h and <dir>/RuntimeBuiltins.cpp from the given
builtin JavaScript sources. Builtin ids and script-origin names derive from the
file names (weak-ref.js -> BuiltinId::kWeakRef, "internal/weak-ref.js").

options:
  --out-dir <dir>        output directory for the generated files (required)
  --minify               minify sources with esbuild (whitespace + syntax only)
  --check-dir <dir>      directory whose .js files must exactly match the
                         inputs; drift fails the build (CMake's incremental
                         change detection reads the explicit input list, so a
                         new builtin missing from it would otherwise be skipped
                         silently on incremental builds)
  --help                 show this message`;

let args;
try {
  args = parseArgs({
    options: {
      'out-dir': { type: 'string' },
      minify: { type: 'boolean', default: false },
      'check-dir': { type: 'string' },
      help: { type: 'boolean', default: false },
    },
    allowPositionals: true,
  });
} catch (e) {
  console.error(e.message);
  console.error(USAGE);
  process.exit(1);
}
if (args.values.help) {
  console.log(USAGE);
  process.exit(0);
}
const outDir = args.values['out-dir'];
const inputs = args.positionals;
if (!outDir || inputs.length === 0) {
  console.error('error: --out-dir and at least one input file are required');
  console.error(USAGE);
  process.exit(1);
}

// Stable ordering regardless of shell glob order, so output never churns.
inputs.sort((a, b) => basename(a).localeCompare(basename(b)));

if (args.values['check-dir']) {
  const present = readdirSync(args.values['check-dir'])
    .filter((f) => f.endsWith('.js'))
    .sort();
  const actual = inputs.map((f) => basename(f)).sort();
  if (JSON.stringify(present) !== JSON.stringify(actual)) {
    const missing = present.filter((f) => !actual.includes(f));
    const stale = actual.filter((f) => !present.includes(f));
    console.error(`error: the RUNTIME_BUILTIN_JS list in CMakeLists.txt is out of sync with ${args.values['check-dir']}`);
    if (missing.length) console.error(`  add:    ${missing.join(', ')}`);
    if (stale.length) console.error(`  remove: ${stale.join(', ')}`);
    process.exit(1);
  }
}

const builtins = [];
for (const file of inputs) {
  if (!existsSync(file)) {
    console.error(`error: no such file: ${file}`);
    process.exit(1);
  }
  if (!file.endsWith('.js')) {
    console.error(`error: builtins must be .js function bodies, got: ${file}`);
    console.error('(.mjs/source-text modules are deliberately unsupported — see docs/ns-builtin-modules.md)');
    process.exit(1);
  }
  const stem = basename(file).replace(/\.js$/, '');
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(stem)) {
    console.error(`error: file name must be kebab-case .js: ${file}`);
    process.exit(1);
  }
  let source = readFileSync(file, 'utf8');
  if (args.values.minify) {
    // Lazy import: esbuild is only needed when minification is requested.
    const esbuild = await import('esbuild');
    source = (await esbuild.transform(source, {
      minifyWhitespace: true,
      minifySyntax: true,
      legalComments: 'none',
    })).code;
  }
  const id = 'k' + stem.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
  builtins.push({ stem, id, origin: `internal/${stem}.js`, source });
}

const ids = builtins.map((b) => `    ${b.id},`).join('\n');
const header = `// generated by tools/js2c.mjs - do not edit
#ifndef RUNTIMEBUILTINS_H_
#define RUNTIMEBUILTINS_H_

#include <cstddef>

namespace tns {

enum class BuiltinId : unsigned {
${ids}
    kCount,
};

struct BuiltinSource {
    const char* name;    // script origin, e.g. "internal/weak-ref.js"
    const char* source;  // NUL-terminated UTF-8
    size_t length;       // bytes, excluding the NUL
};

const BuiltinSource& GetBuiltinSource(BuiltinId id);

}  // namespace tns

#endif /* RUNTIMEBUILTINS_H_ */
`;

// Byte arrays sidestep every C string-literal escaping pitfall.
function toByteArray(name, text) {
  const bytes = Buffer.from(text, 'utf8');
  const lines = [];
  for (let i = 0; i < bytes.length; i += 16) {
    lines.push('        ' + [...bytes.subarray(i, i + 16)].map((b) => `0x${b.toString(16).padStart(2, '0')},`).join(' '));
  }
  // unsigned char: UTF-8 bytes >= 0x80 are narrowing errors in a char array.
  return `static const unsigned char ${name}[] = {\n${lines.join('\n')}\n        0x00};\n`;
}

const arrays = builtins
  .map((b) => `// ${b.stem}.js\n${toByteArray(`kSource${b.id.slice(1)}`, b.source)}`)
  .join('\n');
const entries = builtins
  .map((b) => `        {"${b.origin}", reinterpret_cast<const char*>(kSource${b.id.slice(1)}), sizeof(kSource${b.id.slice(1)}) - 1},`)
  .join('\n');
const impl = `// generated by tools/js2c.mjs - do not edit
#include "RuntimeBuiltins.h"

namespace tns {

namespace {

${arrays}
const BuiltinSource kBuiltins[] = {
${entries}
};

}  // namespace

const BuiltinSource& GetBuiltinSource(BuiltinId id) {
    return kBuiltins[static_cast<unsigned>(id)];
}

}  // namespace tns
`;

mkdirSync(outDir, { recursive: true });
// Gradle configures one CMake build per ABI and may run them concurrently
// against this single shared output directory; write through a per-process
// temp file so a concurrent reader never sees a truncated header.
for (const [name, content] of [['RuntimeBuiltins.h', header], ['RuntimeBuiltins.cpp', impl]]) {
  const path = join(outDir, name);
  const tmp = `${path}.${process.pid}.tmp`;
  writeFileSync(tmp, content);
  renameSync(tmp, path);
}
console.log(`js2c: generated ${builtins.length} builtins into ${outDir}`);
