name: "Test Report"
on:
  workflow_run:
    workflows:
      - Pull Request
      - NPM Release
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        with:
          name: Android Runtime Tests
          artifact: android-unit-test-results # artifact name
          path: android_unit_test_results.xml
          reporter: jest-junit # Format of test results
